services:
  postgres:
    image: postgres:16
    container_name: pg_mineiracao
    environment:
      POSTGRES_DB: mineiracaodb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - pgdata_mineiracao:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d mineiracaodb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata_mineiracao:
